name = UoS Off-Canvas Layout
description = A layout for UoS with off-canvas menu, inside the main region
preview = preview.png
template = uos-off-canvas-layout

; Regions
regions[accessibility]      = Accessibility
regions[branding]           = Branding
regions[branding-subarea-1] = Branding Sub Area 1
regions[branding-subarea-2] = Branding Sub Area 2
regions[branding-subarea-3] = Branding Sub Area 3
regions[header]             = Header
regions[help]               = Help
regions[content]            = Content
regions[sidebar_first]      = Left Sidebar
regions[sidebar_second]     = Right Sidebar
regions[footer]             = Footer

; Stylesheets
stylesheets[all][] = css/layouts/uos-off-canvas/uos-off-canvas.layout.css

; Scripts
scripts[] = layouts/uos-off-canvas/assets/off-canvas.js